version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: npm start
    volumes:
      - .:/app

  mongo:
    image: "mongo:5.0.28"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

  mongoexpress:
    image: "mongo-express:1.0.2-18"
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  db-data: